### ISSUE TITLE
Add conda recipe

### ISSUE THREAD

**Issue by sarthakpati** [miurahr/pyppmd#18]
**Is your feature request related to a problem? Please describe.**
Working towards making `py7zr` available on conda.

**Describe the solution you'd like**
Add a conda recipe.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by miurahr** [comment]
I'd like to fix source package and release v0.16.0.
Thank you for hard work!

**Comment by miurahr** [comment]
As of b8f8600 , pyppmd.egg-info/SOURCES.txt is clean.
I think the conda recipe can skip removing it in next update.

**Comment by sarthakpati** [comment]
Could also do the same for py7zr, as well?

**Comment by sarthakpati** [comment]
Is the new version up on pip? I wasn't able to see it...

**Comment by miurahr** [comment]
> Could also do the same for py7zr, as well?

No. Py7zr is pure python library that does not affect the issue.

**Comment by sarthakpati** [comment]
Dunno what to tell you, but these lines are needed for the [recipe](https://github.com/conda-forge/staged-recipes/pull/15527) to succeed [[ref](https://github.com/sarthakpati/staged-recipes/blob/py7zr/recipes/py7zr/meta.yaml#L21)]:

```yaml
    - rm -rf py7zr.egg-info  # [not win]
    - del /s /q py7zr.egg-info  # [win]
```

**Comment by miurahr** [comment]
What is a reason and cause? There is no extension source to be built for py7zr, that has only a python source.
Where is an evident that failed to be *built*?

**Comment by miurahr** [comment]
Here is the cause of the issue that I fixed;  previous code

```
src_root = pathlib.Path(__file__).parent / "lib"
sources = [
    src_root.joinpath(s).as_posix() for s in ["Ppmd7.c", "Ppmd7Dec.c", "Ppmd7Enc.c", "Ppmd8.c", "Ppmd8Dec.c", "Ppmd8Enc.c"]
]
```
produce full path of c source files. so `pyppmd.egg-info/SOURCES.txt` has a full path of CI/CD environment such as `/home/work/pyppmd/pyppmd/lib/Ppmd8.c` that breaks MSVC compilation on Windows from source package.

A fix is change it with relative path.
 `sources = ['lib/Ppmd7.c', 'lib/Ppmd8.c', 'lib/Ppmd8Dec.c', 'lib/Ppmd7Enc.c', 'lib/Ppmd8Enc.c', 'lib/Ppmd7Dec.c']` 



https://github.com/miurahr/pyppmd/commit/518bf951edcfcead3a46178b8b722d43375afb91

**Comment by sarthakpati** [comment]
Cool, this is merged!

https://github.com/conda-forge/pyppmd-feedstock/pull/5#event-4997730832
