### ISSUE TITLE
About API

### ISSUE THREAD

**Issue by animalize** [miurahr/pyppmd#2]
If there are some variants of PPMd, could consider an unified API suitable for these.

PPMd was designed for text compression, so pyppmd can provide some text-related APIs, such as encoding/decoding, line break, etc.

If need help, you may @ me.

**Comment by miurahr** [comment]
Yes, PPMd is designed for text then you are right. I'm wandering what is pythonic way for that.
I've also interested in supporting PPMd variants not only ver.H also ver.I that used in RAR.

**Comment by miurahr** [comment]
Ppmd7Encoder, Ppmd7Deocder is actually a low level API. We can define high level API that accept encoding, line-break and PPMd version.

**Comment by animalize** [comment]
Need to be very familiar with PPMd and Python, and stand on the user's perspective.
Designing the API may be the most challenging part of the work.

**Comment by miurahr** [comment]
The API should return source data size when it convert encoding. Decoder need an exact size because PPMd decoder designs to produce more data even when input data is exhausted.

**Comment by miurahr** [comment]
Because Ppmd8 now uses end mark In v0.15.0. decompressor can know a length of output data.
So API does not need to return raw data size when string is passed and encoded to UTF-8, it just return compressed data.

An data format of end mark is as same and subset of RAR compression.

**Comment by miurahr** [comment]
For unified API, there are more spaces to be able to improve.
