### ISSUE TITLE
Better license

### ISSUE THREAD

**Issue by miurahr** [miurahr/pyppmd#5]
**Describe the bug**
There are mixture of  licenses,  Public Domain or LGPLv2+ (c code from p7zip, that derivative from 7-zip) and BSD-3.

It is better to change to LGPLv2+ that is clean.

**Comment by miurahr** [comment]
Only compatible license is LGPLv2+. so I've changed to it.

**Comment by cielavenir** [comment]
@miurahr 

- Ppmd7 code can be obtained from LZMA SDK https://www.7-zip.org/sdk.html which is public domain
- Ppmd8 code is a part of 7-zip, but the header says public domain. Also, explicit permission has been issued in https://sourceforge.net/p/sevenzip/discussion/45797/thread/8de79baf/ .

I suppose it is safe to license pyppmd under BSD License.

**Comment by cielavenir** [comment]
@miurahr May I have your opinion?

**Comment by miurahr** [comment]
There is no problem.

**Comment by cielavenir** [comment]
sure (when I find more "liberal" source (here I mean LZMA SDK for example) I tend to switch to it, but it is all up to you)
